---
name: Upload S3Bucket
on:
  push:
    branches:
      - main
jobs:
  CypressTestReport:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: HTML_Report
          path: cypress/reports/Result
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.MY_AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: cypress/reports/Result
